Update python-tests.yml with package name change.
The tests stopped running when the package was introduced.

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -26,13 +26,14 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
+        python -m pip install adaptive_time
         pip install flake8
-        if [ -f code/requirements.txt ];
-        then pip install -r code/requirements.txt;
-        else
-          echo "Cannot find code/requirements.txt, failing."
-          exit 1
-        fi
+        # if [ -f code/requirements.txt ];
+        # then pip install -r code/requirements.txt;
+        # else
+        #   echo "Cannot find code/requirements.txt, failing."
+        #   exit 1
+        # fi
     - name: Lint with flake8
       run: |
         # stop the build if there are Python syntax errors or undefined names
@@ -44,4 +45,4 @@ jobs:
         echo "Directory"
         echo "${{ github.workspace }}"
         echo `ls`
-        python -m unittest
+        python -m unittest adaptive_time/tests/*.py
