More fixes python-tests.yml

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -26,14 +26,14 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        python -m pip install code  # Installs `adaptive_time`
         pip install flake8
-        # if [ -f code/requirements.txt ];
-        # then pip install -r code/requirements.txt;
-        # else
-        #   echo "Cannot find code/requirements.txt, failing."
-        #   exit 1
-        # fi
+        if [ -f code/requirements.txt ];
+        then pip install -r code/requirements.txt;
+        else
+          echo "Cannot find code/requirements.txt, failing."
+          exit 1
+        fi
+        python -m pip install -e code  # Installs `adaptive_time`        
     - name: Lint with flake8
       run: |
         # stop the build if there are Python syntax errors or undefined names
